export const CHANGE_IMAGE_PAGE = 'CHANGE_IAMGE_PAGE';

export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_REQUEST';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';

export const FETCH_SINGLE_IMAGE_REQUEST = 'FETCH_SINGLE_IMAGE_REQUEST';
export const FETCH_SINGLE_IMAGE_SUCCESS = 'FETCH_SINGLE_IMAGE_SUCCESS';
export const FETCH_SINGLE_IMAGE_FAILURE = 'FETCH_SINGLE_IMAGE_FAILURE';
